#!/bin/zsh

function cmkd {
    mkdir -pv -- $1 && cd -P -- $1
}

function acp {
    git add .
    git commit -m "$1"
    git push origin HEAD
}

function gh {
    grep "$1" $HISTFILE --color=auto
}

# convert m3u8
function blobvidl {
    ffmpeg -i "$1" -bsf:a aac_adtstoasc -vcodec copy -c copy -crf 50 "$2"
}

# for runit
function renable {
    sudo ln -s /etc/runit/sv/$1 /run/runit/service/
    sudo sv start $1
}

function rdisable {
    sudo rm /run/runit/service/$1
}
