#!/bin/zsh

function cmkd {
    mkdir -pv -- $1 && cd -P -- $1
}

function acp {
    git add .
    git commit -m "$1"
    git push origin HEAD
}

function gh {
    grep "$1" $HISTFILE --color=auto
}

# convert m3u8
function blobvidl {
    ffmpeg -i "$1" -bsf:a aac_adtstoasc -vcodec copy -c copy -crf 50 "$2"
}

# add audio to video
function ffaudio {
    ffmpeg -i "$1" -i "$2" -c:v copy -map 0:v -map 1:a -y merged-audio.mp4
}

# extract audio from video
function ffeaudio {
    ffmpeg -i "$1" -vn -ac 2 extracted-audio.mp3
}

# for runit
function renable {
    sudo ln -s /etc/runit/sv/$1 /run/runit/service/
    sudo sv start $1
}

function rdisable {
    sudo rm /run/runit/service/$1
}
