#!/usr/bin/zsh

# PROMPT="%{$fg[yellow]%}%n %{$reset_color%}at %{$fg[magenta]%}%M %{$reset_color%}in %{$fg[green]%}%1~ "$'\n'"%{$reset_color%}» "
# RPROMPT="%{$fg[blue]%}[%{$fg[red]%}%*%{$fg[blue]%}]%{$reset_color%}"

# PROMPT="[%{$fg[white]%}%1~%{$reset_color%}]$ "

# PROMPT="%{$fg[yellow]%} %{$fg[magenta]%}ﰲ %{$fg[white]%}%1~"$'\n'"%{$fg[blue]%}%{$reset_color%} "

# PROMPT="%{$fg[yellow]%} %{$fg[magenta]%} %{$fg[white]%}%~"$'\n'"%{$reset_color%}🐧 "

# PROMPT="%{$fg[yellow]%} %{$fg[magenta]%} %{$fg[white]%}%~"$'\n'"%{$fg[blue]%}%{$reset_color%}  "

# PROMPT="%B%{$fg[blue]%}%~%{$reset_color%} %{$fg[green]%}%{$reset_color%}%b  "

# PROMPT="%(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ )"

# PROMPT='%{$fg_bold[blue]%}%~%{$reset_color%} %(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ ) '

PROMPT='%B%{$fg[green]%}(%n) %(?:◆ :%{$fg[red]%}✖%{$fg[green]%} %U$?%u )%~ %(?:%{$fg[magenta]%}❯%{$fg[green]%}:❯)❯❯ %{$reset_color%}%b'
