#!/bin/bash

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Basic aliases
alias \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -Iv" \
    mkdir="mkdir -pv"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# commands too long
alias \
	ka="killall" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
    yt="youtube-dl --add-metadata -i" \
    ws="windscribe" \
    svn="svn --config-dir \"$XDG_CONFIG_HOME/subversion\"" \
    gpa="git remote | xargs -I R git push R" # push to all remotes

# package managers
alias \
    p="sudo pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query"

# init systems
alias \
	ru="sudo rc-update" \
	rs="sudo rc-service" \
    sct="sudo systemctl"

# long dev commands
alias \
    pas="php artisan serve" \
    pat="php artisan test" \
    pr="pnpm run"

command -v thefuck >/dev/null && eval $(thefuck --alias)
