#!/bin/bash

export PATH="$HOME/.config/composer/vendor/laravel/installer/bin:$PATH"
export PATH="$HOME/.config/composer/vendor/symfony/bin:$PATH"
export PATH="$HOME/.local/share/npm/bin:$PATH"
export PATH="$HOME/.local/share/pnpm:$PATH"
