#!/bin/sh

# xinput --set-prop "SynPS/2 Synaptics TouchPad" "Synaptics Palm Detection" 1 &

xrdb -merge "$HOME/.config/X11/.Xresources"

numlockx &                                           # enable numlock on startup
xwallpaper --zoom $(tail ~/.local/share/bg -n 1) &   # setting background
picom --experimental-backends &                      # starting compositor
unclutter &                                          # disable mouse cursor when startionary
exec bspwm
