#!/bin/sh

xinput --set-prop "SynPS/2 Synaptics TouchPad" \
    "Synaptics Palm Detection" 1 &                      # palm detection

xrdb -merge "$XDG_CONFIG_HOME/x11/xresources" &         # merging xresources

startup=("numlockx" "dunst" "unclutter" "sxhkd" "picom --experimental-backends" "dwmblocks" "setbg" "clipmenud" "mpd")

for pgr in "${startup[@]}"; do
    pidof -s "${pgr%% *}" || "$($pgr)" &                # starting programs
done >/dev/null 2>&1

exec dwm
