#!/bin/sh

bspc rule -r "*"

killall polybar
polybar default 2>/dev/null &

xsetroot -cursor_name left_ptr &

bspc monitor -d "1: " "2: " "3: 﫸" "4: " "5: " "6: " "7: " "8: " "9:  "

bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config split_ratio 0.55
bspc config focus_follows_pointer true

bspc config normal_border_color	"#1c2023"
bspc config focused_border_color "#c7ccd1"

bspc config border_width 2
bspc config window_gap 25
