#! /bin/sh

bspc rule -r "*"

pgrep -x sxhkd > /dev/null || sxhkd &

xsetroot -cursor_name left_ptr &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color	"#1d2433"
bspc config active_border_color	"#171c28"
bspc config focused_border_color "#33145e"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color "#ef6b73"

###---Monitor And Desktop Settings----###
bspc config top_padding 32
bspc config bottom_padding 0
bspc config left_padding 7
bspc config right_padding 7
bspc config border_width 2
bspc config window_gap 10
